# default configuration
baseURL = "https://saucelabs.github.io"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Sauce Labs Open Source"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 2

[[menu.main]]
URL = "docs"
name = "Docs"
weight = 3

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/saucelabs_logo_white.png"
# theme color
theme_color = "#AC1414"
# contact info
phone = "+880 2544 658 256"
email = "opensource@saucelabs.com"
address = "116 New Montgomery St, 3rd Floor San Francisco, CA 94105 USA"
# meta description
author = "Sauce Labs Open Source Program Office"
description = "Website with contents for the Sauce Labs Open Source Program Office"
# google analitycs
google_analitycs_id = "" # Your ID
# copyright
copyright = "&copy; 2020 Sauce Labs Inc., all rights reserved. SAUCE and SAUCE LABS are registered trademarks owned by Sauce Labs Inc. in the United States, EU, and may be registered in other jurisdictions."


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

#footer
[params.footer]
enable = true

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-world"
URL = "https://saucelabs.com/"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/sauce-labs/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/saucelabs"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/saucelabs/"
